In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sys
pi = np.pi

from IPython.display import Image
PicPath='C:/Users/17613/Pictures/Jupyter/'


list1 = [[4, 3, 2], [2, 1, 4]]

array = np.array(list1)

print(array)

b = array.argsort(axis = 0)

print(b)

array.sort(axis = 1)

print(array)



list2 = [40, 10, 20, 30]
array = np.array(list2)
vsort = array.argsort()
print(array)
print(vsort)

array[vsort]

type(vsort)

type(array)

tv = np.random.rand(14)

vsort = tv.argsort()

tv[vsort]



[[4 3 2]
 [2 1 4]]
[[1 1 0]
 [0 0 1]]
[[2 3 4]
 [1 2 4]]
[40 10 20 30]
[1 2 3 0]


array([0.1676488 , 0.24427002, 0.29557565, 0.30678457, 0.36519453,
       0.37509713, 0.42028519, 0.49700822, 0.56329004, 0.60220858,
       0.61157793, 0.86227806, 0.87847817, 0.884491  ])