In [1]:
import numpy as np

In [2]:
a = np.arange(4).reshape(2,2)

In [3]:
a

array([[0, 1],
       [2, 3]])

In [4]:
b = a

In [5]:
a*b

array([[0, 1],
       [4, 9]])

In [6]:
np.dot(a,b)

array([[ 2,  3],
       [ 6, 11]])

In [7]:
a * b

array([[0, 1],
       [4, 9]])

In [8]:
x = qt.coherent_dm(5, 1.25)

NameError: name 'qt' is not defined

In [9]:
X

NameError: name 'X' is not defined

In [10]:
x

NameError: name 'x' is not defined